

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sevkikaragol
 */
public class Ekran5 extends javax.swing.JFrame {

    /**
     * Creates new form Ekran5
     */
    public Ekran5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1320, 710));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconClose.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(940, 10, 80, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turkiyeSiyasiHaritasi.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1300, 664);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1320, 710);

        pack();
    }// </editor-fold>                        
    
    Image imgsiyah=new ImageIcon(this.getClass().getResource("iconClose.png")).getImage();
    Image imgkirmizi=new ImageIcon(this.getClass().getResource("iconEnter.png")).getImage();
    Image imgplace=new ImageIcon(this.getClass().getResource("placeHolder.png")).getImage();
    Image imgplace2=new ImageIcon(this.getClass().getResource("pin.png")).getImage();
    
    
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {                                     
       
       JOptionPane.showMessageDialog(this,"Rota görüntüleme işlemi bitti.Çıkış yapılıyor...");
       this.setVisible(false);
        System.exit(0);
       
      
    }                                    

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {                                     
       jLabel2.setIcon(new ImageIcon(imgkirmizi));
    }                                    

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {                                    
        jLabel2.setIcon(new ImageIcon(imgsiyah));
    }                                   

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
          g.setColor(Color.black);
        
        int i=1;
        int x=0;
       
       while(i<Main.rotalarYeni.get(4).size()){
          
       if(Main.noktalar.contains(Main.rotalarYeni.get(4).get(i))){
            g.drawImage(imgplace2, Main.koordinat[Main.rotalarYeni.get(4).get(i)][0]-8,
      Main.koordinat[Main.rotalarYeni.get(4).get(i)][1]+5,rootPane);
       }    
       else{   
       g.drawImage(imgplace, Main.koordinat[Main.rotalarYeni.get(4).get(i)][0]-8,
      Main.koordinat[Main.rotalarYeni.get(4).get(i)][1]+5,rootPane);
       }
       
        
      g.drawLine(Main.koordinat[Main.rotalarYeni.get(4).get(i-1)][0]+8,
      Main.koordinat[Main.rotalarYeni.get(4).get(i-1)][1]+39,
      Main.koordinat[Main.rotalarYeni.get(4).get(i)][0]+8,
      Main.koordinat[Main.rotalarYeni.get(4).get(i)][1]+39);  
      
        
      i++;
          
      
        
        
        
       }
        
        
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ekran5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ekran5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ekran5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ekran5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ekran5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
